pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Terraform RDS build') {
            steps {
                withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding',
                credentialsId: 'awscreds',
                accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                sh '''
                cd Infra_Setup/RDS-PostgresSql
                ls -l
                terraform init
                echo "Terraform action is --> ${action}"
                ls -l
                terraform ${action} -auto-approve
                '''
                }
            }
        }    
    }
}

