pipeline {
    agent any
    
    stages {
        stage('Clone Repository') {
            steps {
            sh '''
            whoami
            git clone git@github.com:sohailumd/toyota-demo.git
            cd toyota-demo
            pwd
            ls
            '''
            }
        }    
    }
}

