pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'us-east-2'
    }

    stages {
        stage('AWS Creds') {
            steps {
                 withAWS(credentials: 'awscreds', region: 'us-east-2')
            }
        }
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
    
        stage ("terraform init") {
            steps {
                sh '''
                cd toyota-demo/RDS-PostgresSql
                ls -l
                terraform init
                '''
            }
        }
        
        stage ("plan") {
            steps {
                sh '''
                cd toyota-demo/RDS-PostgresSql
                ls -l
                terraform plan -var -var="access_key=${access_key}" -var="secret_access_key=${secret_access_key}"
                '''
            }
        }

        stage ("Action") {
            steps {
                sh '''
                echo "Terraform action is --> ${action}"
                cd toyota-demo/RDS-PostgresSql
                ls -l
                terraform ${action} -auto-approve -var="access_key=${access_key}" -var="secret_access_key=${secret_access_key}"
                '''
           }
        }
    }
}
    
