pipeline {
    agent any

    stages {
        stage('AWS Creds') {
            steps {
                withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding', 
                credentialsId: 'awscreds', 
                accessKeyVariable: 'AWS_ACCESS_KEY_ID', 
                secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                    sh "aws s3 ls"
                }
            }
        }
    }
}
    
